### ISSUE TITLE
Cross-platform support for test infrastructure

### ISSUE THREAD

**Issue by glennsl** [BuckleTypes/bs-containers#21]
Having looked into this a bit, ava (which we currently use) seems like a poor backend for a cross-platform test toolkit because it is so tightly coupled to the test source code. On test failure ava will print the source code that the assertion stack trace points to, which if abstracted will always just be some internal piece of code. Jest seems like it would suitable as a JS backend.

@bordoley has the same need, and has made [reUnit](https://github.com/facebookincubator/immutable-re/tree/master/reUnit/src) as a quick and dirty cross-platform test framework and has plans to integrate it with Jest. We could perhaps build further on that, but should in any case try to consolidate our efforts. Also see [bs-jest](https://github.com/BuckleTypes/bs-jest)

cc @dorafmon

**Comment by dorafmon** [comment]
I have no problem with switching to `bs-jest` for test backend, the choice of using `ava` is made before there is `bs-jest`. So if I understand you correctly, what we are proposing here is:

1. Have a unified test interface, like `reUnit.rei`
2. For this interface we have two separate implementations, one uses a native backend, probably improve upon `reUnit.rei` and then also have a JS backend, built around `bs-jest`? 

Also, do you think it is possible for us to support some kind of source map for `bs-jest` so when a test fail it reports back the location in ml/re file, not the JS file (although it is fairly easy to find out, because BS output is quite readable.)

**Comment by glennsl** [comment]
The js backend certainly doesn't have to be bs-jest, it might be simpler to just copy or define the externals needed internally. But I think Jest is a suitable js backend. Also, bs-jest is designed in a way that makes it easy to swap out the assertion library (but not the test runner) and could be useful as inspiration.

I don't think source mapping will be very useful when the assertions are abstracted, since the stack traces will just point to internals. You'd have to provide __LOC__ for each and every test I think, which really doesn't seem worth it to me. I just use the test name, which works fine if you have good test names and a well-ordered test suite.

**Comment by bordoley** [comment]
I'm very supportive of any solution that cleanly integrates with jest for unit testing and would be willing to take it on as a dependency in imm.re. Beyond jest's top notch test runner, the code coverage reports would be of significant value. 

My only real requirement is that the test dsl be decoupled from jest itself so that a minimal test runner such as ounit's can be used for native testing.

**Comment by glennsl** [comment]
I've created a POC of a cross platform test framework here: https://github.com/glennsl/poc-xtest

It's based on ocamlbuild and bsb, with each build process including a separate platform-specific `Impl` module that does the actual work. Note that in the Jest implementation the `run` function is a no-op since jest runs each test file separately, while the native implementation needs a main function that collects and runs the tests, which could cause some tests to be skipped by mistake.

**Comment by dorafmon** [comment]
@glennsl could you open a PR to integrate bs-containers with poc-xtest? Thanks.

**Comment by glennsl** [comment]
There's a couple things I think we should sort out first:
1. The problems that might be caused by jest and native tests being collected and run differently
2. The style of assertions. Should it be like jest to better match its output: `expect true |> toEqual false`, or the simpler `assertEqual true false`, or something else?
3. How to print native test values? This might require some design changes.
4. Should we integrate with OUnit instead of rolling our own native runner?

**Comment by bordoley** [comment]
Is ounit actively maintained? Looking at the test runner, it doesn't appear to do anything particularly fancy. I'll admit a preference to focus on Jest integration first, as it is far more advance afaict (parallelized test runs, code coverage reports, etc.).

Re: assertion style, I originally implemented ReUnit to use  expect true |> toEqual false, but quickly started to find it annoying and instead switched to an Expect module of assertions tests. see:  https://github.com/facebookincubator/immutable-re/blob/master/reUnit/src/ReUnit.rei#L18

Here are some examples in use: https://github.com/facebookincubator/immutable-re/blob/master/test/IterableTest.re#L21

**Comment by glennsl** [comment]
I've zero experience with OUnit, I've just been told that's the thing to use. I have a hard time trusting code from a repo that throws `TypeError`s at me though. I'm fine with rolling our own.

Also fine with either assertion style, though the reunit style does seem simpler to both implement and use. And it doesn't require an `open`. So maybe I should try that then :)
